using System;
using System.Globalization;
using System.IO;
using System.Linq;
using CADWorkAssistant.Core.Models;
using CADWorkAssistant.Core.Verification;
using CADWorkAssistant.Documents.Reports;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using PdfSharp.Pdf.IO;

namespace CADWorkAssistant.Documents.Pdf;

/// <summary>
/// QuantityReportModel(Documents.Reports, Excel과 완전히 공유) -> 실제 .pdf (Milestone 10). PDFsharp/
/// MigraDoc을 직접 다루는 유일한 클래스다 - Core/AutoCAD는 이 타입을 참조하지 않는다(§41-43).
/// Print-to-PDF/OS printer/Chromium/Node/Word Interop을 쓰지 않는다(§46-47, §97-100) - PDFsharp가
/// 순수 관리 코드로 OOXML이 아닌 PDF 바이너리를 직접 만들기 때문에 외부 프로세스 없이 항상 성공한다.
/// </summary>
public sealed class QuantityPdfBuilder
{
    // Excel(QuantityWorkbookBuilder)과 같은 팔레트를 문서 가독성 우선으로 옮긴다(§58-60) - 흑백
    // 출력에서도 읽혀야 하므로 강조색은 제목 정도로만 쓴다.
    private static readonly Color AccentColor = new(0x1D, 0x6F, 0x8F);
    private static readonly Color MutedTextColor = new(0x52, 0x61, 0x70);
    private static readonly Color HeaderFill = new(0xEE, 0xF2, 0xF5);
    private static readonly Color BorderColor = new(0xCA, 0xD3, 0xDC);

    public PdfExportResult BuildAndSave(QuantityReportModel model, PdfExportOptions options, string targetPath)
    {
        WindowsKoreanFontResolver.EnsureRegistered();

        var document = new Document();
        // §65, §133: 실제 작성자를 알 수 없으니 지어내지 않는다 - Title/Subject만 채운다. Creator는
        // PDFsharp이 자기 자신("PDFsharp")으로 자동 채운다 - 임의 회사명을 별도로 넣지 않는다.
        document.Info.Title = $"{model.ProjectName} 수량산출근거서";
        document.Info.Subject = "CAD Work Assistant 수량 산출 및 검산 보고서";

        DefineStyles(document);

        var section = document.AddSection();
        section.PageSetup.PageFormat = PageFormat.A4;
        section.PageSetup.Orientation = Orientation.Portrait;
        section.PageSetup.TopMargin = "2cm";
        section.PageSetup.BottomMargin = "1.6cm";
        section.PageSetup.LeftMargin = "2cm";
        section.PageSetup.RightMargin = "2cm";

        BuildHeader(section, model);
        BuildFooter(section);

        BuildCoverAndSummary(section, model, options);

        if (model.Rows.Count > 0)
        {
            var detailTitle = section.AddParagraph("항목별 산출근거");
            detailTitle.Style = "Heading1";
            detailTitle.Format.PageBreakBefore = true;

            foreach (var row in model.Rows)
            {
                BuildDetailBlock(section, row, options);
            }
        }

        var renderer = new PdfDocumentRenderer { Document = document };
        renderer.RenderDocument();
        // §169: PageCount는 Save() 이전에 읽어야 한다 - Save 이후 PdfDocument는 read-only가 되어
        // PageCount 접근 자체가 InvalidOperationException을 던진다(실제로 겪은 문제).
        var pageCount = renderer.PdfDocument.PageCount;

        SaveAtomically(renderer, targetPath);

        return new PdfExportResult { FilePath = targetPath, RecordCount = model.TotalCount, PageCount = pageCount };
    }

    private static void DefineStyles(Document document)
    {
        var normal = document.Styles["Normal"]!;
        normal.Font.Name = "Malgun Gothic";
        normal.Font.Size = 9.5;
        normal.Font.Color = Colors.Black;

        var heading1 = document.Styles.AddStyle("Heading1", "Normal");
        heading1.Font.Size = 14;
        heading1.Font.Bold = true;
        heading1.Font.Color = AccentColor;
        heading1.ParagraphFormat.SpaceAfter = "0.3cm";

        var heading2 = document.Styles.AddStyle("Heading2", "Normal");
        heading2.Font.Size = 11;
        heading2.Font.Bold = true;
        heading2.ParagraphFormat.SpaceBefore = "0.2cm";
        heading2.ParagraphFormat.SpaceAfter = "0.15cm";
        heading2.ParagraphFormat.KeepWithNext = true;

        var muted = document.Styles.AddStyle("Muted", "Normal");
        muted.Font.Color = MutedTextColor;
        muted.Font.Size = 8.5;
    }

    private static void BuildHeader(Section section, QuantityReportModel model)
    {
        var header = section.Headers.Primary.AddParagraph();
        header.AddText($"{model.ProjectName} · 수량 산출 및 검산 보고서");
        header.Format.Font.Size = 8.5;
        header.Format.Font.Color = MutedTextColor;
        header.Format.Borders.Bottom.Width = 0.5;
        header.Format.Borders.Bottom.Color = BorderColor;
        header.Format.SpaceAfter = "0.2cm";
    }

    private static void BuildFooter(Section section)
    {
        var footer = section.Footers.Primary.AddParagraph();
        footer.Format.Alignment = ParagraphAlignment.Center;
        footer.Format.Font.Size = 8;
        footer.Format.Font.Color = MutedTextColor;
        footer.AddText("Generated by CAD Work Assistant · TRSN CLARUS");
        footer.AddTab();
        footer.AddText("Page ");
        footer.AddPageField();
        footer.AddText(" / ");
        footer.AddNumPagesField();

        section.PageSetup.FooterDistance = "0.8cm";
        var tabStops = footer.Format.TabStops;
        tabStops.ClearAll();
        tabStops.AddTabStop(section.PageSetup.PageWidth - section.PageSetup.LeftMargin - section.PageSetup.RightMargin,
            TabAlignment.Right);
    }

    // ------------------------------------------------------------------
    // 표지 / 프로젝트 요약 / 수량 요약 표
    // ------------------------------------------------------------------
    private static void BuildCoverAndSummary(Section section, QuantityReportModel model, PdfExportOptions options)
    {
        var title = section.AddParagraph(options.Scope == QuantityExportScope.VerifiedOnly
            ? "검토 완료 수량 보고서"
            : "수량 산출 및 검산 보고서");
        title.Style = "Heading1";
        title.Format.Font.Size = 18;

        AddInfoLine(section, "프로젝트", model.ProjectName);
        if (!string.IsNullOrWhiteSpace(model.Site))
        {
            AddInfoLine(section, "현장", model.Site!);
        }

        if (!string.IsNullOrWhiteSpace(model.Client))
        {
            AddInfoLine(section, "발주처", model.Client!);
        }

        if (!string.IsNullOrWhiteSpace(model.Description))
        {
            AddInfoLine(section, "설명", model.Description!);
        }

        AddInfoLine(section, "작성일", model.GeneratedAt.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture));

        var summary = section.AddParagraph();
        summary.Format.SpaceBefore = "0.3cm";
        summary.Format.SpaceAfter = "0.3cm";
        summary.AddText(model.TotalCount == 0
            ? "내보낼 수량이 없습니다."
            : $"전체 수량 {model.TotalCount}건 · 검토 완료 {model.VerifiedCount}건 · 확인 필요 {model.NeedsReviewCount}건 · " +
              $"검산 오류 {model.VerificationErrorCount}건 · 미검산 {model.Rows.Count(r => r.VerificationSeverity is null)}건");
        summary.Format.Font.Bold = true;

        // §139: Error/Review가 있으면 요약 페이지에서 바로 알린다 - 자동 경고를 숨기지 않는다.
        var needsAttention = model.Rows.Any(r =>
            r.VerificationSeverity == VerificationSeverity.Error || r.VerificationSeverity == VerificationSeverity.Review);
        if (needsAttention)
        {
            var warning = section.AddParagraph("주의가 필요한 수량이 포함되어 있습니다. 항목별 상세의 검산 결과를 확인하세요.");
            warning.Format.Font.Color = MutedTextColor;
            warning.Format.Font.Italic = true;
            warning.Format.SpaceAfter = "0.3cm";
        }

        if (model.Rows.Count == 0)
        {
            return;
        }

        BuildSummaryTable(section, model);
    }

    private static void AddInfoLine(Section section, string label, string value)
    {
        var p = section.AddParagraph();
        p.AddFormattedText($"{label}: ", TextFormat.Bold);
        p.AddText(value);
        p.Format.SpaceAfter = "0.05cm";
    }

    private static void BuildSummaryTable(Section section, QuantityReportModel model)
    {
        var table = section.AddTable();
        table.Borders.Width = 0.5;
        table.Borders.Color = BorderColor;
        table.Format.Font.Size = 9;

        table.AddColumn("1.1cm");
        table.AddColumn("2.2cm");
        table.AddColumn("5.2cm");
        table.AddColumn("2.4cm");
        table.AddColumn("1.4cm");
        table.AddColumn("2.4cm");
        table.AddColumn("1.8cm");

        var header = table.AddRow();
        header.HeadingFormat = true;
        header.Shading.Color = HeaderFill;
        header.Format.Font.Bold = true;
        string[] headers = { "No.", "구분", "내역", "수량", "단위", "검산", "검토" };
        for (var i = 0; i < headers.Length; i++)
        {
            header.Cells[i].AddParagraph(headers[i]);
        }

        foreach (var row in model.Rows)
        {
            var r = table.AddRow();
            r.Cells[0].AddParagraph(row.Index.ToString(CultureInfo.InvariantCulture));
            r.Cells[1].AddParagraph(row.TypeDisplayName);
            r.Cells[2].AddParagraph(row.Description);
            var qtyPara = r.Cells[3].AddParagraph(FormatQuantity(row.Value, row.DecimalPlaces));
            qtyPara.Format.Alignment = ParagraphAlignment.Right;
            r.Cells[4].AddParagraph(row.Unit);
            r.Cells[5].AddParagraph(VerificationText(row));
            r.Cells[6].AddParagraph(QuantityReviewStatusDisplay.Label(row.ReviewStatus));
        }
    }

    // ------------------------------------------------------------------
    // 항목별 산출근거 - 각 QuantityReportRow를 하나의 블록으로
    // ------------------------------------------------------------------
    private static void BuildDetailBlock(Section section, QuantityReportRow row, PdfExportOptions options)
    {
        var heading = section.AddParagraph($"{row.Index:00}. {row.Description}");
        heading.Style = "Heading2";

        AddDetailLine(section, "구분", row.TypeDisplayName, keepWithNext: true);
        AddDetailLine(section, "최종 수량", $"{FormatQuantity(row.Value, row.DecimalPlaces)} {row.Unit}", keepWithNext: true);

        if (options.IncludeCalculationDetails)
        {
            if (row.RawValue.HasValue && row.SourceUnit is not null)
            {
                AddDetailLine(section, "원본값",
                    $"{row.RawValue.Value.ToString("N3", CultureInfo.InvariantCulture)} {row.SourceUnit} → " +
                    $"{FormatQuantity(row.Value, row.DecimalPlaces)} {row.Unit}", keepWithNext: true);
            }

            AddDetailLine(section, "측정방법", row.MeasurementSourceDisplay, keepWithNext: true);

            if (options.IncludeSourceDrawing)
            {
                AddDetailLine(section, "원본 도면", row.SourceDrawingFileName ?? "-", keepWithNext: true);
            }

            AddDetailLine(section, "CAD 객체", $"{row.ObjectCount}개", keepWithNext: true);

            // §21-22, §96: 구조화 metadata에서 이미 만들어진 사람이 읽는 문자열을 그대로 쓴다 - PDF에서
            // 다시 파싱해서 재구성하지 않는다. 과거 기록이라 산식 자체가 없으면 안전하게 안내 문구로
            // 대체한다(Crash 금지, §22).
            var formulaLine = section.AddParagraph();
            formulaLine.AddFormattedText("산출식: ", TextFormat.Bold);
            formulaLine.AddText(row.CalculationExpression ?? "세부 입력정보 없음");
            formulaLine.Format.KeepWithNext = true;
            formulaLine.Format.SpaceAfter = "0.05cm";
        }

        if (options.IncludeVerification)
        {
            var verificationLine = section.AddParagraph();
            verificationLine.AddFormattedText("검산: ", TextFormat.Bold);
            verificationLine.AddText(VerificationText(row));
            if (row.IsVerificationStale)
            {
                verificationLine.AddText(" (재검산 필요)");
            }

            verificationLine.Format.KeepWithNext = row.VerificationCheckLines.Count > 0;
            verificationLine.Format.SpaceAfter = "0.05cm";

            foreach (var line in row.VerificationCheckLines)
            {
                var checkPara = section.AddParagraph($"  {ToPdfSafeGlyph(line)}");
                checkPara.Format.Font.Size = 8.5;
                checkPara.Format.KeepWithNext = true;
                checkPara.Format.SpaceAfter = "0.02cm";
            }
        }

        var reviewLine = section.AddParagraph();
        reviewLine.AddFormattedText("검토: ", TextFormat.Bold);
        reviewLine.AddText(QuantityReviewStatusDisplay.Label(row.ReviewStatus));
        reviewLine.Format.KeepWithNext = options.IncludeReviewNotes && !string.IsNullOrWhiteSpace(row.ReviewNote);
        reviewLine.Format.SpaceAfter = "0.05cm";

        if (options.IncludeReviewNotes && !string.IsNullOrWhiteSpace(row.ReviewNote))
        {
            var notePara = section.AddParagraph($"  {row.ReviewNote}");
            notePara.Format.Font.Size = 8.5;
            notePara.Format.Font.Color = MutedTextColor;
        }

        var spacer = section.AddParagraph();
        spacer.Format.SpaceAfter = "0.35cm";
        spacer.Format.Borders.Bottom.Width = 0.25;
        spacer.Format.Borders.Bottom.Color = BorderColor;
    }

    private static void AddDetailLine(Section section, string label, string value, bool keepWithNext)
    {
        var p = section.AddParagraph();
        p.AddFormattedText($"{label}: ", TextFormat.Bold);
        p.AddText(value);
        p.Format.KeepWithNext = keepWithNext;
        p.Format.SpaceAfter = "0.05cm";
    }

    private static string FormatQuantity(decimal value, int decimalPlaces) =>
        value.ToString("N" + Math.Max(decimalPlaces, 0), CultureInfo.InvariantCulture);

    /// <summary>Excel(QuantityWorkbookBuilder.VerificationCellText)과 같은 Core.Verification.
    /// VerificationSeverityDisplay를 재사용해 텍스트 라벨은 Cross-format으로 완전히 동일하다(§94,
    /// §144-148). 글리프만 <see cref="ToPdfSafeGlyph"/>를 거친다 - 텍스트 라벨이 항상 함께 있어
    /// 흑백 출력에서도 상태를 구분할 수 있다(§131-132).</summary>
    private static string VerificationText(QuantityReportRow row) =>
        ToPdfSafeGlyph($"{VerificationSeverityDisplay.Glyph(row.VerificationSeverity)} {VerificationSeverityDisplay.Label(row.VerificationSeverity)}");

    /// <summary>Milestone 10 §131 - 실제로 렌더링해서 확인해보니 Windows의 맑은 고딕에는 Dingbats
    /// 블록 글리프가 없어 Core.Verification.VerificationSeverityDisplay.Glyph()의 ✓(U+2713, Pass)가
    /// PDF에서 빈 사각형(tofu)으로 깨졌다 - !(Review)/×(Error)/—(없음)는 이 폰트에 이미 있어
    /// 문제없었다. PDF에서만 ✓를 ○(U+25CB, 실제 렌더링 확인됨 - 한국 문서에서 흔한 ○/× 표기와도
    /// 자연스럽게 어울린다)로 치환한다. Core나 Excel은 건드리지 않는다 - Excel은 뷰어가 시스템 폰트로
    /// 자동 대체해 이미 정상 표시된다(§94의 "텍스트는 공유, 렌더링은 각자"와 같은 원칙).</summary>
    private static string ToPdfSafeGlyph(string text) => text.Replace('✓', '○');

    /// <summary>§81-85: Excel과 같은 원자적 저장 원칙 - 같은 폴더에 임시 파일로 저장 → 다시 열어
    /// 최소 구조(페이지 존재)를 검증 → 성공했을 때만 원래 경로로 원자적 교체.</summary>
    private static void SaveAtomically(PdfDocumentRenderer renderer, string targetPath)
    {
        var directory = Path.GetDirectoryName(Path.GetFullPath(targetPath)) ?? ".";
        Directory.CreateDirectory(directory);
        var tempPath = Path.Combine(directory, $"~cwa_{Guid.NewGuid():N}.pdf");

        try
        {
            renderer.PdfDocument.Save(tempPath);

            using (var verify = PdfReader.Open(tempPath, PdfDocumentOpenMode.Import))
            {
                if (verify.PageCount == 0)
                {
                    throw new InvalidOperationException("Generated PDF has no pages.");
                }
            }

            File.Move(tempPath, targetPath, overwrite: true);
        }
        catch
        {
            TryDelete(tempPath);
            throw;
        }
    }

    private static void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
        catch
        {
            // §85와 동일 원칙: 정리 실패 자체가 원래 오류를 가리면 안 된다.
        }
    }
}
